---
apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: jt-proj2-apply-bom
  namespace: aap
spec:
  connection_secret: aap-controller-api
  name: proj2-apply-bom
  organization: Default
  project: AAP Demo (GitHub)
  playbook: playbooks/apply_proj2_bom.yml
  inventory: Demo Inventory
