---
apiVersion: v1
kind: Namespace
metadata:
  name: proj2
  labels:
    app.kubernetes.io/managed-by: aap-demo
  annotations:
    openshift.io/description: "Demo workload namespace (proj2 BOM, copy of proj1 pattern)"
    openshift.io/display-name: "Proj2 Demo"
