---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-vm-01
  namespace: proj2
  labels:
    app.kubernetes.io/name: fedora-vm
    app.kubernetes.io/instance: fedora-vm-01
    app.kubernetes.io/managed-by: aap-demo
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora-vm-01
        app.kubernetes.io/name: fedora-vm
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
          rng: {}
        machine:
          type: pc
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/kubevirt/fedora-container-disk-images:41
            imagePullPolicy: IfNotPresent
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              ssh_pwauth: true
              disable_root: true
              hostname: fedora-vm-01-proj2
              timezone: UTC
              packages:
                - qemu-guest-agent
                - curl
                - vim-minimal
              runcmd:
                - ["systemctl", "enable", "--now", "qemu-guest-agent.service"]
              users:
                - default
                - name: fedora
                  groups: [wheel]
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  plain_text_passwd: changeme-proj2-vm-01
