---
- name: Apply proj2 BOM
  hosts: localhost
  gather_facts: false
  vars:
    project_slug: proj2
    bom_dir_abs: "{{ playbook_dir | dirname }}/projects/{{ project_slug }}/bom"
    bom_files:
      - namespace.yaml
      - serviceaccount.yaml
      - networkpolicy.yaml
      - vm-fedora-01.yaml
      - vm-fedora-02.yaml
  tasks:
    - ansible.builtin.import_tasks: tasks/apply_bom.yml
